version: '3.9'

services:
  create_service:
    build: ./create_service
    ports:
      - "8001:8001"
    env_file:
      - ./create_service/.env
    depends_on:
      - read_service
      - update_service
      - delete_service
    restart: always

  read_service:
    build: ./read_service
    ports:
      - "8002:8002"
    env_file:
      - ./read_service/.env
    restart: always

  update_service:
    build: ./update_service
    ports:
      - "8003:8003"
    env_file:
      - ./update_service/.env
    restart: always

  delete_service:
    build: ./delete_service
    ports:
      - "8004:8004"
    env_file:
      - ./delete_service/.env
    restart: always
