version: "3.9"

services:
  delete_service:
    build:
      context: .
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URI=mongodb://54.145.134.230:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo3
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
