# Use a base Python image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the dependencies file
COPY requirements.txt ./

RUN pip install --upgrade pip
# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files into the container
COPY . .

# Expose the internal port of the container
EXPOSE 9100

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9100", "--reload"]
