version: '3.8'

services:
  delete_users:
    build: ./DeleteUsers
    container_name: delete_users_service
    ports:
      - "5001:5000"
    env_file:
      - ./DeleteUsers/.env
    restart: always
    depends_on:
      - edit_users

  edit_users:
    build: ./EditUsers
    container_name: edit_users_service
    ports:
      - "5002:8080"
    env_file:
      - ./EditUsers/.env
    restart: always

  view_users:
    build: ./ViewUsers
    container_name: view_users_service
    ports:
      - "5003:9100"
    env_file:
      - ./ViewUsers/.env
    restart: always
