# Imagen base de Node.js
FROM node:18

# Configurar directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto del microservicio
EXPOSE 8050

# Comando de inicio
CMD ["node", "src/server.js"]
